name: 'Pull Request Preview'
description: 'Github Action for previewing changes in static websites'
inputs:
  GITHUB_TOKEN:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  PA_TOKEN:
    description: 'Personal access token with permissions to push to preview-repo'
    required: true
  PREVIEW_REPOSITORY:
    description: 'Repository the pull request preview should be pushed to'
    required: true
  GITHUB_PAGES_BASE:
    description: 'Base URL of the configured Github Pages'
    required: true
  FORCE_PAT:
    description: 'Whether the personal access token should be used for all actions'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.PA_TOKEN }}
    - ${{ inputs.PREVIEW_REPOSITORY }}
    - ${{ inputs.GITHUB_PAGES_BASE }}
    - ${{ inputs.FORCE_PAT }}
