name: 'Pull Request Preview'
description: 'Github Action for previewing changes in static websites'
inputs:
  GITHUB_TOKEN:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  REPOSITORY:
    description: 'Repo to push previews to'
    required: true
  PA_TOKEN:
    description: 'Personal access token with permissions to push to preview-repo'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.pa_token }}
    - ${{ inputs.repository }}
